title: Your Blog Name
description: I am writing about my experiences as a naval navel-gazer.
author:
  name: Your Name Here,
  email: youremailaddress@example.com,
  url: https://example.com/about-me/
